queue: Hosted VS2017

trigger:
  - master
  - rel/*

variables:
  BuildConfiguration: Release

steps:
- template: .vsts-shared.yml
  parameters:
    signSteps:
    - task: PowerShell@2
      displayName: Authenticode Sign artifacts
      inputs:
        filePath: Tools\Sign-Package.ps1
      env:
        SignClientUser: $(SignClientUser)
        SignClientSecret: $(SignClientSecret)
        ArtifactDirectory: $(Build.ArtifactStagingDirectory)\Packages
