parameters: 
  signSteps: []
  
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables
    
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: scripts/setversion.csproj
    arguments: -c $(BuildConfiguration)  
  displayName: Set Version
  condition: eq(variables['system.pullrequest.isfork'], false)
  
- powershell: |
    mkdir $Env:Temp\packages
    msbuild /restore /t:pack /p:PackageOutputPath=$(System.DefaultWorkingDirectory)\artifacts
  displayName: Build

- task: CopyFiles@2
  inputs:
    Contents: '$(System.DefaultWorkingDirectory)\artifacts\MSBuild.Sdk.Extras.*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)\Packages'
    flattenFolders: true

- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Package
  condition: eq(variables['system.pullrequest.isfork'], false)    