parameters:
  signSteps: []

steps:
- task: BatchScript@1
  displayName: Setup Environment Variables
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true

- task: NuGetToolInstaller@0
  displayName: Put NuGet in Path
  inputs:
    versionSpec: 4.7.0

- task: DotNetCoreCLI@2
  displayName: Set Version
  condition: eq(variables['system.pullrequest.isfork'], false)
  inputs:
    command: build
    projects: Tools\SetVersion.csproj
    arguments: -c $(BuildConfiguration)

- powershell: |
    mkdir $Env:Temp\Packages
    msbuild /Restore /t:Pack
  displayName: Build

- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    Contents: '$(System.DefaultWorkingDirectory)\~Packages\**\*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Packages'
    flattenFolders: true

- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  condition: eq(variables['system.pullrequest.isfork'], false)
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Package
